### PR TITLE
Topo guacamole

### PR DESCRIPTION
**Pull request by networkRob**
Added the topology specific `user-mapping.xml` file, so the lab frontend will load correctly based off topo.  Updated the `atdFiles` service script to copy the topology specific user-mapping.xml file to the `/etc/guacamole/` directory.

### CODE REVIEW

**Comment by networkRob** [comment]
For testing of this PR, perform the following by ssh'ing to the labvm and getting to bash:
```
sudo atdServiceUpdater.py
cd /tmp/atd
sudo git checkout -b topo-guacamole origin/topo-guacamole
sudo bash labvm/services/atdFiles/atdFiles.sh
cd ~/
```
Now from the ATD landing page, you can click on the `LabFrontend` link to view the correct eos devices.

**Comment by brokenpackets** [comment]
This seems to work, but requires the user log out and back in to guacamole (reload with clearing cache doesn't seem to work, but could be a local system issue). Thanks!

**Comment by networkRob** [comment]
This would occur at boot so shouldn't be seen.

**Comment by networkRob** [comment]
Closing this PR as it will be incorporated into the `cvp-green-release` branch

**Pull request closed without merging**
