### PR TITLE
Further Updates to RATD Configlets and Options

### PR DESCRIPTION
**Pull request by DimitriCapetz**
After testing I found a few more issues and some deprecated commands.  This should fix those.  I also adjusted the menu options to apply the base configlet to any all devices.  Previously there was an issue moving between different lab sections (from standard to ring) that would cause Mgmt IP validation to fail.  This should fix that as well.

### CODE REVIEW

**Comment by networkRob** [comment]
@DimitriCapetz Can you place the DNS configuration and `management api` config section into the `ATD-INFRA` configlet? I think that would be a good place for those configs.

**Comment by DimitriCapetz** [comment]
For sure.  Would you want me to do that for the DC-Latest as well?  I'll commit to RATD only for now.

**Comment by networkRob** [comment]
Let's do RATD for now.  Yes we should do this for the dc-latest as well in another pr

**Comment by DimitriCapetz** [comment]
Hey, thoughts on moving "ip routing" and the "service routing protocols" (ArBGP) into the ATD-INFRA configlet?  It's on every device and will make things a bit more universal.

**Comment by networkRob** [comment]
I agree on that suggestion.  We should follow best practices on any shared config that is infrastructure or shared for the topology should be placed in the ATD-INFRA cfglet

**Comment by DimitriCapetz** [comment]
Should be in line now.  Please let me know if anything else looks amiss.

**Pull request merged**
