### PR TITLE
Delivering the 1st of the Troubleshooting labs and guides

### PR DESCRIPTION
**Pull request by bingbucks**

### CODE REVIEW

**Comment by bingbucks** [comment]
Note that there are also other troubleshooting lab changes in here, which are not complete, but hopefully are benign. We were sharing the same branch. I have the latest set of commits and tested with everything up until that point.

@RyanM-Arista Any concerns?

**Comment by RyanM-Arista** [comment]
Yes, Jumphost menu needs to be either modified or changed to the Media labs style otherwise it will error out.

**Comment by bingbucks** [comment]
Not right now though, I think that portion is commented out? I'm not hitting it on the branch.

**Comment by bingbucks** [comment]
@jorisc90 This was a mistake and got swept into version control by accident. How do you want to handle it? Want me to delete and re-PR?

**Comment by jorisc90** [comment]
Either that or just remove it with the next update. Both are fine with me.

**Comment by networkRob** [comment]
Don't re-PR it, just remove it from the PR.

**Comment by bingbucks** [comment]
@networkRob In the beginning recall that we were working off the "datacenter" topology until the "datacenter-latest" become the (default) topology of choice. If someone spun up "datacenter" (which I did not test because I thought we were abandoning it) the legacy changes to topologies/datacenter/files/MenuOptions.yaml may cause an issue due to the jumphost menu out of range?

Also, did we remove "cvx.rst" from topologies/datacenter-latest/labguides/source/index.rst? It may have slipped back in. Do we want it anymore?

**Comment by networkRob** [comment]
We have not removed `cvx.rst` from the atd's so that should stay in place.  @ccnPeon has been doing work on a new login menu that can handle different sub-menus.  So this is something I would like to see how it integrates with that and if we should get the new menu in place first.

**Comment by ccnPeon** [comment]
I am working to roll this into the menu update as well so we might be able to kill 2 birds with one pull request. I see you have configlets for hosts, but they are not being applied to any of your labs in the yaml files. Is this correct? If so, do you still want all of those configlets to come over?

**Comment by bingbucks** [comment]
@ccnPeon One is actually applied to Host1 (from MenuOptions.yaml) and a "default" is applied to Host2 (to take it out of play):

```
  tshoot-intro:
    spine1:
      - "tshoot-spine1-Tshoot-intro"
    spine2:
      - "tshoot-default"
    leaf1:
      - "tshoot-leaf1-Tshoot-intro"
    leaf2:
      - "tshoot-leaf2-Tshoot-intro"
    leaf3:
      - "tshoot-default"
    leaf4:
      - "tshoot-default"
    host1:
      - "tshoot-host1-Tshoot-intro"
    host2:
      - "tshoot-default"

```

**Comment by ccnPeon** [comment]
Ok. I updated the yaml in the menus to match the changes. Just noting that currently I can see that the tshoot-sp and tshoot-automation are commented out. I have that reflected as well.

**Comment by bingbucks** [comment]
@ccnPeon Yes, those other 2 labs ("SP" and "Automation") are products that @RyanM-Arista , Fran Loehmann, and Andy Stirpe (can't find their GitHUb handles) are working on (on the same branch in the my PR request). We were hoping to time all the changes in one big delivery, but I think we'll have to phase it.

**Comment by networkRob** [comment]
Closing as the code has been merged from another branch.

**Pull request closed without merging**
