### PR TITLE
Release 2020-09-14

### PR DESCRIPTION
**Pull request by networkRob**
Removes apt, pip and nodejs installs from atdFiles. These pkgs are now installed in the base jumphost image versioned 2020-09-11

High level release notes:
```
	▪	additions to devcontainer (zsh and github cli)
	▪	EVPN lab guide updated to remove next-hop unchanged on leafs and send-community
	▪	gitConfigletSync timeout increased to 900 seconds
	▪	task check implemented when executing labs
	▪	keyboard interrupt logging
	▪	backend jumphost updates
	▪	increased logging for lab execution
```

### CODE REVIEW

**Comment by ccnPeon** [comment]
@networkRob How do we go about testing this? I believe it is in the backend.

**Comment by networkRob** [comment]
@ccnPeon Correct, the changes are in the backend. The new jumphost build being referenced has the pkgs installed when that image was built. So atdFiles doesn't need to install them. I believe we tested this in the beta topology when we were getting ready to merge this into dev.

**Review by ccnPeon — APPROVED** [review]
These changes reflect changes in the backend and were tested by me. Approved for dev merge.

**Review by ccnPeon — APPROVED** [review]
I have done some testing on this and have not seen any issues.

**Pull request merged**
